services:
    postgres:
        container_name: postgres
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DATABASE}
            - POSTGRES_PORT=${POSTGRES_PORT}
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - payment-backend

    redis:
        container_name: redis
        image: redis:latest
        restart: always
        environment:
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - ${REDIS_PORT}:6379
        volumes:
            - redis_data:/data
        networks:
            - payment-backend

volumes:
    postgres_data:
    redis_data:

networks:
    payment-backend:
